config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard' , as: "dashboard"
  get 'profile/:user_id', to: 'pages#profile', as: 'user_profile'
  get 'teachers/', to: 'pages#index', as: 'teachers'
  # get 'teachers/:id', to: 'pages#show', as: 'teacher'

  resources :programs do
    resources :batches, only: [:index, :show, :new, :create, :edit]
    resources :reviews, only: [:new, :create]
    resources :lessons, only: [:create]
  end

  resources :batches, only: [:update, :destroy] do
    resources :students, only: [:index, :new, :create]
    post '/slots_students', to: "slots_students#create_all", as: "slots_create"
  end

  resources :lessons, only: [] do
    resources :slots, only: [:new, :create, :destroy]
  end

  resources :reviews, only: [:edit, :destroy, :update]
  resources :slots_students, only: [:destroy]
end

app/models/program.rb
class Program < ApplicationRecord
  DURATIONS = ['1', '2', '4', '6']
  DISCIPLINES = ["Yoga", "Pilates", "Dance", "Meditation"]
  LEVELS = ["Beginner", "Intermediate", "Advanced"]
  LANGUAGES = ["French", "English", "Spanish", "German", "Japanese"]
  belongs_to :user
  has_many :batches, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :lessons, dependent: :destroy
  has_many_attached :medias
  validates :name, presence: true
  validates :discipline, presence: true, inclusion: { in: DISCIPLINES }
  validates :level, presence: true, inclusion: { in: LEVELS }
  validates :target, presence: true
  validates :duration, presence: true, inclusion: { in: DURATIONS }
  validates :price, presence: true, numericality: true
  validates :medias, presence: true
  validates :description, length: { minimum: 3 }
  validates :language, presence: true, inclusion: { in: LANGUAGES }
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:search]
      filter_params = {}
      params[:search].each_key do |search_field|
        # unless params[:search][search_field].length.zero?
        if params[:search][search_field].instance_of?(Array)
          search_values = params[:search][search_field]
        else
          search_values = [params[:search][search_field]] # search_value est tjrs un array.
        end
        unless search_values == [""]
          filter_params[search_field] = search_values.reject { |x| x.length.zero? }
        end
      end
      @programs = Program.where(filter_params)
    else
      @programs = Program.all
    end
  end

  def show
    @lesson = Lesson.new
    @review = Review.new
  end

  def new
    @program = Program.new
  end

  def edit; end

  def update
    if @program.update(program_params)
      redirect_to program_path(@program), notice: 'Program was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @program.destroy
    redirect_to dashboard_path, notice: 'Program was successfully deleted.'
  end

  def create
    @program = Program.new(program_params)
    @program.user = current_user
    current_user.teacher = true
    current_user.save!
    if @program.save
      redirect_to program_path(@program), notice: 'Program was successfully created.', data: { turbo: false }
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def program_params
    params.require(:program).permit(:name, :discipline, :level, :target, :duration, :price, :description, :language, medias: [])
  end

  def set_program
    @program = Program.find(params[:id])
  end
end

app/views/programs/_card.html.erb
<div class="card-trip">
  <div class="latest">
    <%# <img src="https://images.unsplash.com/photo-1522787345986-d5c7885a889e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format" alt="image"> %>
    <%= cl_image_tag program.medias.first.key %>
    <div class="more-info">
      <%= link_to "More info", program_path(program), class: 'btn btn-primary btn-sm', data: { turbo: false } %>
    </div>
    <div class="card-trip-infos">
      <div class="avatar-card">
        <%= link_to user_profile_path(program.user) do %>
          <%= cl_image_tag program.user.profile_picture.key %>
        <% end %>
        <%# <img src="https://kitt.lewagon.com/placeholder/users/krokrob" alt="user avatar"> %>
      </div>
      <div class="card-trip-infos-desc">
        <h2><%= program.name.capitalize %></h2>
        <ul>
          <li><i class="fa-solid fa-dumbbell"></i> <%= program.discipline %></li>
          <li><i class="fa-solid fa-clock"></i> <%= pluralize program.duration, "month" %></li>
          <% case program.level %>
          <% when 'Beginner' %>
            <% color_level = 'success-green' %>
          <% when 'Intermediate' %>
            <% color_level = 'orange' %>
          <% when 'Advanced' %>
            <% color_level = 'red' %>
          <% end %>
          <br>
          <%# <div class="card-trip-carac" style="padding-top: 4px;"> %>
          <%# <ul style="padding-left: 8px;"> %>
          <li>
            <span class="text-<%= color_level %>"><i class="fa-solid fa-signal"></i> </span> <%= program.level %>
          </li>
          <li>
            <i class="fa-solid fa-flag"></i> <%= program.language %>
          </li>
          <br>
          <li>
            <i class="fa-solid fa-euro-sign"></i> <%= program.price %>
          </li>
            <%# </ul> %>
            <%# </div> %>
        </ul>
      </div>
      <%# <div class="card-trip-price"> %>
        <%# <><%= program.price %>
      <%# </div> %>
    </div>
  </div>
</div>

app/views/programs/_carousel.html.erb
<div id="carouselExampleControlsNoTouching" class="carousel slide carousel-fade" data-bs-touch="false" data-bs-interval="true" data-bs-ride="carousel">
  <% programs = @programs.shuffle %>
  <div class="carousel-indicators">
    <% programs.each_with_index do |program, i| %>
      <% if program.medias.first == programs.first.medias.first %>
        <button type="button" data-bs-target="#carouselExampleControlsNoTouching" data-bs-interval="4000"  data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <% else %>
        <button type="button" data-bs-target="#carouselExampleControlsNoTouching" data-bs-interval="4000" data-bs-slide-to="<%= i %>" aria-label="Slide <%= i+1 %>"></button>
      <% end %>
    <% end %>
  </div>
  <div class="carousel-inner">
    <% programs.each do |program| %>
      <% if program.medias.first == programs.first.medias.first %>
        <div class="carousel-item active" data-bs-interval="4000">
          <%= cl_image_tag program.medias.first.key, :width=>1000, :height=>500, :gravity=>"auto", :crop=>"fill", :background=>"white", class: 'd-block w-100', data: 'color: lightblue' %>
          <div class="carousel-caption d-none d-md-block">
            <h3>
            <%= link_to program.name.capitalize, program_path(program) %>
             by
            <%= link_to program.user.first_name, user_profile_path(program.user) %>
            </h3>
            <p><%= truncate program.description, length: 500, separator: ' ' %></p>
          </div>
        </div>
        <% else %>
        <div class="carousel-item" data-bs-interval="4000">
          <%= cl_image_tag program.medias.first.key, :width=>1000, :height=>500, :gravity=>"auto", :crop=>"fill",  :background=>"white", class: 'd-block w-100', data: 'color: lightblue' %>
          <div class="carousel-caption d-none d-md-block">
            <h3>
            <%= link_to program.name.capitalize, program_path(program) %>
             by
            <%= link_to program.user.first_name, user_profile_path(program.user) %>
            </h3>
            <p><%= truncate program.description, length: 500, separator: ' ' %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControlsNoTouching" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControlsNoTouching" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/programs/_dashboardcard.html.erb
<div class="card-dashboard">
  <div class="latest">
    <%= cl_image_tag program.medias.first.key %>
    <div class="more-info">
      <%= link_to new_program_batch_path(program) do%>
        <button class="button_plus"></button>
      <% end %>
    </div>
    <div class="card-dashboard-infos">
      <div class="card-dashboard-infos-desc">
        <h2><%= program.name %></h2>
        <% if program.batches.length != 0  %>
          <strong><h5 style="padding-left: 4px;"><%= pluralize program.batches.count, 'batch' %> :</h5></strong>

        <%# <div class="scroll"> %>
          <ul style="list-style: none;">
            <% program.batches.each do |batch|%>
              <%= link_to program_batch_path(program, batch) do %>
                <li>#<%= batch.id %> - <%= link_to batch_students_path(batch) do %>
                  <i class='fa-solid fa-person-half-dress'></i> <%= batch.users.count %> / <%= batch.max_students %>
                <% end %></li>
              <% end %>
            <% end %>
          </ul>
        <%# </div> %>
        <% else %>
          <strong><h5><%= link_to "You have no batch yet", new_program_batch_path(program) %></h5></strong>
        <% end %>
      </div>
    </div>
    <div class="edit">
      <%= link_to edit_program_path(program) do %>
        <i class="fa-solid fa-pen"></i>
      <% end %>
    </div>
    <div class="addlesson">
      <%= link_to 'Program details', program_path(program) %>
    </div>
    <div class="delete">
      <%= link_to program_path(program), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this program?" }, class: "ms-3" do %>
        <i class="fa-solid fa-trash"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/programs/_form.html.erb
<div class="mx-4">
  <%= simple_form_for @program do |f| %>
    <%= f.input :name, placeholder: "ex: Yoga for Beginners, Learn Twist,...", class: "form-control" %>
    <%= f.input :discipline,
      as: :radio_buttons,
      collection_wrapper_tag: 'div',
      collection_wrapper_class: 'discipline-wrapper',
      item_wrapper_class: 'discipline-item',
      input_html: {class: 'discipline-selector'},
      collection: Program::DISCIPLINES %>
    <%= f.input :target, placeholder: "ex: gain muscles, improve flexibility, ...", class: 'form-control' %>
    <div class="mb-3", data-controller="range-price">
      <%= f.input :price, as: :range, label: 'Price (€)', class: "form-control",
      input_html: {min: 0, max: 500, step:10, data: { action: "input->range-price#displayPrice"}} %>
      <span id="display" data-range-price-target="display"> 250€ </span>
    </div>
    <%= f.input :duration, label: 'Average length (months)', selected: 4, class: "form-control", collection: Program::DURATIONS %>
    <%= f.input :level,
      as: :radio_buttons,
      collection_wrapper_tag: 'div',
      collection_wrapper_class: 'level-wrapper',
      item_wrapper_class: 'level-item',
      input_html: { class: 'level-selector' },
      collection: Program::LEVELS %>
    <%= f.input :medias, as: :file, required: true, input_html: { multiple: true } %>
    <%= f.input :description, placeholder: "Enter a short description of your program",required: true %>
    <%= f.input :language, class: "form-control", collection: Program::LANGUAGES, selected: 'English' %>

    <div class="d-flex justify-content-center">
      <div class="text-center">
        <p><%= f.button :submit, "Submit", class: "btn btn-primary" %></p>
        <p><%= link_to "Cancel", dashboard_path %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/programs/_latestcard.html.erb
<div class="card-trip">
  <div class="container mt-5 mb-5">
    <div class="d-flex justify-content-center row">
      <div class="col-md-10">
        <div class="row p-2 bg-white">
          <div class="col-lg-6 mt-1"><%= cl_image_tag program.medias.first.key %></div>
          <div class="col-lg-6 mt-1">
            <h2><%= program.name %></h2>
            <ul>
              <li><%= program.user.first_name %>'s program</li>
              <li><%= program.level %></li>
              <li><%= program.target %></li>
              <li><%= program.duration %> month</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/programs/_lesson.html.erb
<div data-controller="popover">
  <%= render 'shared/lesson-popup', lesson: lesson %>
  <div data-action="mouseenter->popover#show mouseleave->popover#hide" style="position: relative;">
    <div class="lesson-card">
      <div class="lesson-card-number">
        <%= lesson.number %>
      </div>
      <div class="lesson-card-title">
        <%= lesson.title %>
      </div>
    </div>
  </div>
</div>

app/views/programs/_teacher-small.html.erb
<%= link_to user_profile_path(user) do %>
  <%= cl_image_tag user.profile_picture.key, :transformation=>[{gravity: 'head', :crop=>"crop"}, {:height=>80, :width=>80, :crop=>"fill"}], class: "teacher-avatar rounded-circle" %>
<% end %>

app/views/programs/_teacher.html.erb
<%= link_to user_profile_path(user), class: 'mx-4' do %>
  <%= cl_image_tag user.profile_picture.key, :transformation=>[{gravity: 'head', :crop=>"crop"}, {:height=>150, :width=>150, :crop=>"fill"}], class: "teacher-avatar rounded-circle" %>
<% end %>

app/views/programs/create.html.erb
<h1>Programs#create</h1>
<p>Find me in app/views/programs/create.html.erb</p>

app/views/programs/destroy.html.erb
<h1>Programs#destroy</h1>
<p>Find me in app/views/programs/destroy.html.erb</p>

app/views/programs/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>Edit my program</h1>
      <div class="card bg-light" style="padding: 24px;">
        <%= render 'form', program: @program %>
      </div>
    </div>
  </div>
</div>

app/views/programs/index.html.erb
<div class="container">
  <% if @programs == Program.all %>
    <h1><%= pluralize Program.all.count, 'program' %> available</h1>
  <% else %>
    <h1><%= pluralize @programs.count, 'program' %> found</h1>
  <% end %>
  <div class="col-12">
    <div class="row align-items-center justify-content-around d-flex mt-4">
      <div class="col-10 align-items-center justify-content-around d-flex">
        <div class="col mx-2">
          <%= simple_form_for(:search, url: programs_path, method: :get, class: 'form-inline') do |f| %>
          <%= f.input :discipline, label: 'Discipline of choice:', collection: Program::DISCIPLINES, class: "form-group mb-2", required: false %>
        </div>
        <div class="col mx-2">
          <%= f.input :level, label: 'Your level?', collection: Program::LEVELS, class: "form-group mb-2", required: false %>
        </div>
        <div class="col mx-2">
          <%= f.input :duration, label: 'For how long? (month(s))', collection: Program::DURATIONS, class: "form-group mb-2", required: false %>
        </div>
        <div class="col mx-2">
          <%= f.input :language, label: 'Language?', collection: Program::LANGUAGES, class: "form-group mb-2", required: false %>
        </div>
      </div>
      <div class="col-2">
        <%= f.submit "Browse programs!", class: "btn btn-warning mt-3", data: { turbo: false } %>
      </div>
      <% end %>
    </div>
  </div>
      <%#= f.submit "Reset filters", class: "btn btn-secondary" %>
  <% if @programs.count.zero? %>
    <div class="text-center">
      <h5 style="margin-top: 32px;"><i class="fa-solid fa-hand-holding-heart"></i> There are no programs matching your criteria (yet). You may <%= link_to 'try again', programs_path, class: 'text-blue', data: { turbo: false } %>.</h5>
    </div>
  <% else %>
    <div class="cards">
      <% @programs.each do |program| %>
        <%= render 'card', program: program %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/programs/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>Create a new program</h1>
      <div class="card bg-light" style="padding: 24px;">
        <%= render 'form', program: @program %>
      </div>
    </div>
  </div>
</div>

app/views/programs/update.html.erb
<h1>Programs#update</h1>
<p>Find me in app/views/programs/update.html.erb</p>