config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard' , as: "dashboard"
  get 'profile/:user_id', to: 'pages#profile', as: 'user_profile'
  get 'teachers/', to: 'pages#index', as: 'teachers'
  # get 'teachers/:id', to: 'pages#show', as: 'teacher'

  resources :programs do
    resources :batches, only: [:index, :show, :new, :create, :edit]
    resources :reviews, only: [:new, :create]
    resources :lessons, only: [:create]
  end

  resources :batches, only: [:update, :destroy] do
    resources :students, only: [:index, :new, :create]
    post '/slots_students', to: "slots_students#create_all", as: "slots_create"
  end

  resources :lessons, only: [] do
    resources :slots, only: [:new, :create, :destroy]
  end

  resources :reviews, only: [:edit, :destroy, :update]
  resources :slots_students, only: [:destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    &copy; BodyBuddy
  </div>
</div>

app/views/shared/_infos.html.erb
<div class="card mb-4">
  <div class="card-body p-0">
    <ul class="list-group list-group-flush rounded-3">
      <li class="list-group-item d-flex justify-content-between align-items-center p-3">
        <p class="mb-0"><i class="fa-solid fa-dumbbell"></i> <%= program.discipline %></p>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center p-3">
        <p class="mb-0"><i class="fa-solid fa-signal"></i> <%= program.level %></p>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center p-3">
        <p class="mb-0"><i class="fa-solid fa-crosshairs"></i> <%= program.target %></p>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center p-3">
        <p class="mb-0"><i class="fa-solid fa-clock"></i> <%= pluralize program.duration, "month" %></p>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center p-3">
        <p class="mb-0"><i class="fa-solid fa-euro-sign"></i> <%= program.price %></p>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center p-3">
        <p class="mb-0"><i class="fa-solid fa-flag"></i> <%= program.language %></p>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_lesson-popup.html.erb
<template data-popover-target="content">
  <div
    data-popover-target="card"
    class='popover__wrapper'
  >
    <p class="popover__content"><%= lesson.description %></p>
  </div>
</template>

app/views/shared/_navbar-hp.html.erb
<div class="container-fluid">
  <%= link_to root_path, data: { turbo: false } do %>
    <%= image_tag "http://res.cloudinary.com/dtegydg3s/image/upload/v1675763317/q0ztt1hj6muug9aa5g6y.png", width: 63, height: 42, id: 'logo' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
        <% if current_user.teacher? %>
          <li class="nav-item">
            <%= link_to "My programs", dashboard_path, class: "nav-link light-color", data: { turbo: false } %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.profile_picture.key, :transformation=>[{gravity: 'head', :crop=>"crop"}, {:height=>50, :width=>50, :crop=>"fill"}], class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="container-fluid">
  <%= link_to root_path, data: { turbo: false } do %>
    <%= image_tag "http://res.cloudinary.com/dtegydg3s/image/upload/v1675763317/q0ztt1hj6muug9aa5g6y.png", width: 63, height: 42 %>
  <% end %>

  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
        <% if current_user.teacher? %>
          <li class="nav-item">
            <%= link_to "My programs", dashboard_path, class: "nav-link light-color", data: { turbo: false } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "All programs", programs_path, class: "nav-link", data: { turbo: false } %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.profile_picture.key, :transformation=>[{gravity: 'head', :crop=>"crop"}, {:height=>45, :width=>45, :crop=>"fill"}], class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>