config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard' , as: "dashboard"
  get 'profile/:user_id', to: 'pages#profile', as: 'user_profile'
  get 'teachers/', to: 'pages#index', as: 'teachers'
  # get 'teachers/:id', to: 'pages#show', as: 'teacher'

  resources :programs do
    resources :batches, only: [:index, :show, :new, :create, :edit]
    resources :reviews, only: [:new, :create]
    resources :lessons, only: [:create]
  end

  resources :batches, only: [:update, :destroy] do
    resources :students, only: [:index, :new, :create]
    post '/slots_students', to: "slots_students#create_all", as: "slots_create"
  end

  resources :lessons, only: [] do
    resources :slots, only: [:new, :create, :destroy]
  end

  resources :reviews, only: [:edit, :destroy, :update]
  resources :slots_students, only: [:destroy]
end

app/views/pages/_student-dashboard.html.erb
<div class="container my-5">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="Infos-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true"><h4>Infos</h4></button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="calendar-tab" data-bs-toggle="tab" data-bs-target="#calendar" type="button" role="tab" aria-controls="calendar" aria-selected="false"><h4>Calendar</h4></button>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab"><%# infos tab %>
      <h2>My batch:</h2>
      <% if current_user.batch.nil? %>
        <p>You are not registered yet. You can <%= link_to "browse programs", programs_path, data: { turbo: false } %>!</p>
      <% else %>
        <div class="col-md-4 mt-3">
          <div class="bike-card">
            <%= render 'programs/dashboardstudentcard', program: @batch.program %>
          </div>
        </div>
      <% end %>
    </div><%# infos tab end%>

    <div class="tab-pane fade" id="calendar" role="tabpanel" aria-labelledby="calendar-tab"><%# calendar tab%>
      <div class="container mt-5">
        <%# calendar %>
        <%= month_calendar(events: @slots) do |date, slots| %>
          <%= date %>
          <% slots.each do |slot| %>
            <div class="slot">
              <p><%= slot.lesson.title %></p>
              <small><%= slot.start_time.strftime("%l:%M %p")%> - <%= (slot.start_time + slot.duration * 3600).strftime("%l:%M %p") %></small>
            </div>
          <% end %>
        <% end %>
        <%# calendar end%>
      </div>
    </div><%# calendar tab end%>
  </div>
</div>

app/views/pages/_synthesis-teacher.html.erb
<div class="card-synthesis-teacher">
  <div class="card-synthesis-teacher-infos">
    <div class="card-synthesis-teacher-infos-desc">
      <h2><%= pluralize current_user.programs.count, 'program' %></h2>
      <% count_batch = 0 %>
      <% count_student = 0 %>
      <% current_user.programs.each do |prg| %>
        <% count_batch += prg.batches.count %>
        <% prg.batches.each { |b| count_student += b.users.count } %>
      <% end %>
      <h2><%= pluralize count_batch, 'batch' %></h2>
      <h2><%= pluralize count_student, 'student' %></h2>
      <h2>Teaching at BodyBuddy since <%= current_user.created_at.strftime("%B %Y") %></h2>
    </div>
    <%# <div class="card-synthesis-teacher-price"> %>
      <%# <><%= program.price %>
    <%# </div> %>
  </div>
</div>

app/views/pages/_teacher-dashboard.html.erb
<div class="container my-5">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="programs-tab" data-bs-toggle="tab" data-bs-target="#programs" type="button" role="tab" aria-controls="programs" aria-selected="false"><h4>Programs</h4></button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="Infos-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true"><h4>Infos</h4></button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="calendar-tab" data-bs-toggle="tab" data-bs-target="#calendar" type="button" role="tab" aria-controls="calendar" aria-selected="false"><h4>Calendar</h4></button>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show" id="home" role="tabpanel" aria-labelledby="home-tab"><%# infos tab %>
      <div class="row">
        <div class="col-2"></div>
        <div class="col-8 justify-content-center">
          <div class="bike-card">
            <%= render 'pages/synthesis-teacher' %>
          </div>
        </div>
        <div class="col-2"></div>
      </div>
    </div><%# infos tab end%>

    <div class="tab-pane fade show active" id="programs" role="tabpanel" aria-labelledby="programs-tab"><%# programs tab%>
      <div class="container mt-4">
        <% if @programs.length > 0 %>
          <h2><%= pluralize @programs.count, 'program' %></h2><br>
          <div class="row">
            <% @programs.each do |program| %>
              <div class="col-md-4 mt-2">
                <div class="bike-card">
                  <%= render 'programs/dashboardcard', program: program %>
                </div>
              </div>
            <% end %>
          </div>
        <% else %>
          <p>You do not have any programs yet. </p>
        <% end %>
        <br>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <h4 style="padding-left: 36px;">Add program</h4>
          <div class="text-right" style="height: 40px; position: relative;">
            <%# <button class="button_plus" data-action="visibility#toggleTargets"></button> %>
            <button class="button_plus" data-bs-toggle="modal" data-bs-target="#new_batch_modal"></button>
          </div>
        </div>
        <div class="col-sm-9">
          <div class="modal fade" id="new_batch_modal" tabindex="-1" aria-labelledby="new_batch_modalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="new_batch_modalLabel">Add a new program</h5>
                </div>
                <div class="modal-body">
                  <%# Program duration: <%= pluralize @program.duration, 'month' %>
                  <br>
                  <%= render 'programs/form', program: Program.new %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div><%# programs tab end%>

    <div class="tab-pane fade" id="calendar" role="tabpanel" aria-labelledby="calendar-tab"><%# calendar tab%>
      <div class="container mt-5">
        <%# calendar %>
        <%= month_calendar(events: @slots) do |date, slots| %>
          <%= date %>
          <% slots.each do |slot| %>
            <div class="slot">
              <p><%= slot.lesson.title %></p>
              <small><%= slot.start_time.strftime("%l:%M %p")%> - <%= (slot.start_time + slot.duration * 3600).strftime("%l:%M %p") %></small>
            </div>
          <% end %>
        <% end %>
        <%# calendar end%>
      </div>
    </div><%# calendar tab end%>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container my-5">
  <% if current_user.teacher? %> <%#teacher page %>
    <div class="bike-card">
      <%= render 'pages/teacher-dashboard' %>
    </div>
  <% else %> <%# student page %>
    <div class="bike-card">
      <%= render 'pages/student-dashboard' %>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="hero-banner" style="margin-bottom: 0">
  <div class="container">
    <div class="hero-banner-content text-center" >
      <h1>BODY<%= image_tag 'http://res.cloudinary.com/dtegydg3s/image/upload/v1675763317/q0ztt1hj6muug9aa5g6y.png', height: '80px', class: "bb_icon" %>BUDDY</h1>
      <br>
      <p>Build your own journey to a balanced life with our online
      <%= image_tag "https://freesvg.org/img/Female-Yoga-Pose-Silhouette-13.png", class: 'bb_icon_small invert', height: '35px' %>
      courses</p>
      <div style="height: 50px"></div>
      <p>
        Select your favorite disciplines, your level and join us!
      </p>
      <div class="row align-center justify-content-center d-flex">
        <%= simple_form_for(:search, url: programs_path, method: :get, class: 'form-inline') do |f| %>
          <div class="d-flex align-center justify-content-center mx-2 mt-3">
            <%= image_tag "https://freesvg.org/img/Female-Yoga-Pose-Silhouette-13.png", class: 'bb_icon_small invert', height: '35px' %>
            <div style="width: 8px;"></div>
            <%= f.input :discipline, as: :check_boxes, input_html: { class: "tag-selector" }, item_wrapper_class: 'tag-item', label: '', collection: Program::DISCIPLINES, class: "form-group mb-2", required: false %>
          </div>
        </div>
      </div>
      <div class="row align-center justify-content-center d-flex">
        <div class="d-flex align-center justify-content-center mx-2">
          <p style='color: white; opacity: .8; font-size: 1.4rem; margin-right: 16px;'><i class="fa-solid fa-signal"> </i></p>
          <%= f.input :level, label: '', as: :check_boxes, collection: Program::LEVELS, input_html: { class: "tag-selector" }, item_wrapper_class: 'tag-item', class: "form-range mb-2", required: false %>
        </div>
      </div>
      <div class="row d-flex justify-content-center">
        <div class="col-6 text-center" style="margin-top: 16px">
          <%= f.submit "Let's go!", class: "btn btn-lg btn-primary", data: { turbo: false } %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-12" style="padding: 0;">
      <%= render 'programs/carousel', programs: Program.all %>
    </div>
  </div>
</div>

<div class="container mb-3">
  <div class="row">
    <div class="col-12 text-center mb-2 mt-4">
      <h1>Discover our programs below</h1>
    </div>
  </div>

  <div class="row">
    <% @programs.first(6).each do |program| %>
      <div class="col-md-4 mt-3">
        <div class="bike-card">
          <%= render 'programs/card', program: program %>
          <div class="bike-card-actions">

          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-12 mt-4 text-center">
      <%= link_to "See all programs", programs_path, class: 'btn btn-primary btn-lg', data: { turbo: false } %>
    </div>
  </div>

  <%# <div class="row"> %>
    <div style="height: 40px">
    </div>
    <div class="col-12 mt-8 mb-2 text-center">
      <h1>Meet our teachers</h1>
    </div>
    <div style="height: 20px">
    </div>
  <%# </div> %>

  <div class="teacher-cards d-flex">
    <% @teachers = User.where(teacher: true).last(4) %>
    <% @teachers.each do |teacher| %>
      <%= render 'programs/teacher', user: teacher %>
    <% end %>
  </div>

  <div class="row">
  <div class="col-12 mt-4 text-center" style="margin-bottom: 80px">
    <%= link_to "See all teachers", teachers_path, class: 'btn btn-primary btn-lg' %>
  </div>
</div>
</div>

app/views/pages/index.html.erb
<div class="container text-center mt-5">
  <h1>All our teachers</h1>
  <div class="row justify-content-center mt-5">
    <% @users.each_slice(4) do |group| %>
      <% group.each do |user| %>
        <div class="col-sm-3 mb-5 mx-3">
          <!-- teacher card -->
          <%= render partial: "programs/teacher", locals: { user: user } %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container">
  <section style="background-color: #eee;">
    <div class="row">
      <h1><%= @user.first_name %>'s profile</h1>
      <p> <% if @user.teacher? %>
          <%= @user.first_name %> has been teaching at BodyBuddy since <%= @user.created_at.strftime("%B %Y") %>
          <% end %>
      </p>
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <%= cl_image_tag @user.profile_picture.key, :transformation=>[{gravity: 'head', :crop=>"crop"}, {:height=>150, :width=>150, :crop=>"fill"}],
            class: 'rounded-circle img-fluid' %>
            <h5 class="my-3"><%= @user.first_name %></h5>
          </div>
        <% if @user.teacher? %>
        </div>
        <div class="card mb-4 mb-lg-0">
          <div class="card-body p-0">
            <ul class="list-group list-group-flush rounded-3">
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <p class="mb-0"><%= @user.description %></p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
               <p class="mb-0"> I teach in <%= @user.language %> !</p>
              </li>
            </ul>
          </div>
        </div>
        <% else %>
        </div>
        <div class="card mb-4 mb-lg-0">
          <div class="card-body p-0">
            <ul class="list-group list-group-flush rounded-3">
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <p class="mb-0"><%= @user.description %></p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
               <p class="mb-0"> I learn in <%= @user.language %> !</p>
              </li>
            </ul>
          </div>
        </div>
        <% end %>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Full Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.first_name %> <%= @user.last_name %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Email</p>
              </div>
              <div class="col-sm-9">
                <% if current_user == @user %>
                  <p class="text-muted mb-0"><%= @user.email %></p>
                <% else %>
                  <p class="text-muted mb-0"><i class="fa-solid fa-xmark"></i> <i class="fa-solid fa-xmark"></i> <i class="fa-solid fa-xmark"></i></p>
                <% end %>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Address</p>
              </div>
              <div class="col-sm-9">
                <% if current_user == @user %>
                  <p class="text-muted mb-0"><%= @user.address %></p>
                <% else %>
                  <p class="text-muted mb-0"><i class="fa-solid fa-xmark"></i> <i class="fa-solid fa-xmark"></i> <i class="fa-solid fa-xmark"></i></p>
                <% end %>
              </div>
            <% unless @user.teacher? %>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Program attended</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"> <%= @user.batch.program.name %></p>
            </div>
             <% end %>
            </div>
          </div>
        </div>
        <% if @user.teacher? %>
        <div class="row">
        <h2><%= @user.first_name %>'s programs</h2>
        <% @user.programs.each do |program| %>
          <div class="col-6">
            <div class="bike-card">
              <%= render 'programs/card', program: program %>
            </div>
          </div>
        <% end %>
        </div>
        <% end %>
    </div>
  </section>
</div>